stages:
  - quality_check

quality_check:
  stage: quality_check
  image: instrumentisto/flutter:latest
  script:
    - flutter gen-l10n
    - dart format --set-exit-if-changed .
    - flutter analyze
  only:
    - merge_requests
    - branches